version: '3.9'

services:
  mongodb:
    container_name: todo-mongodb
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo
      MONGO_INITDB_ROOT_PASSWORD: todo

volumes:
  mongo_data:
